// <auto-generated />
using System;
using Cliq.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cliq.Server.Migrations
{
    [DbContext(typeof(CliqDbContext))]
    [Migration("20241207170420_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cliq.Server.Models.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentCommentId")
                        .HasColumnType("text");

                    b.Property<string>("ParentPostId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("ParentPostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Comment_HasOneParent", "(\"ParentPostId\" IS NOT NULL AND \"ParentCommentId\" IS NULL) OR (\"ParentPostId\" IS NULL AND \"ParentCommentId\" IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = "comment1",
                            Date = new DateTime(2024, 12, 7, 17, 4, 19, 940, DateTimeKind.Utc).AddTicks(9882),
                            ParentPostId = "post1",
                            Text = "I am bob and I am commenting on a post",
                            UserId = "user3"
                        },
                        new
                        {
                            Id = "childComment2",
                            Date = new DateTime(2024, 12, 7, 17, 4, 19, 940, DateTimeKind.Utc).AddTicks(9887),
                            ParentCommentId = "comment1",
                            Text = "I am John responding to Bob",
                            UserId = "user1"
                        },
                        new
                        {
                            Id = "comment3",
                            Date = new DateTime(2024, 12, 7, 17, 4, 19, 940, DateTimeKind.Utc).AddTicks(9890),
                            ParentPostId = "post1",
                            Text = "I am Jane and I am commenting on Bob's post",
                            UserId = "user2"
                        });
                });

            modelBuilder.Entity("Cliq.Server.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", "public");

                    b.HasData(
                        new
                        {
                            Id = "post1",
                            Date = new DateTime(2024, 12, 6, 17, 4, 19, 940, DateTimeKind.Utc).AddTicks(9767),
                            Text = "Hello world! This is my first post.",
                            UserId = "user1"
                        },
                        new
                        {
                            Id = "post2",
                            Date = new DateTime(2024, 12, 7, 5, 4, 19, 940, DateTimeKind.Utc).AddTicks(9788),
                            Text = "Excited to join this platform!",
                            UserId = "user2"
                        },
                        new
                        {
                            Id = "post3",
                            Date = new DateTime(2024, 12, 7, 11, 4, 19, 940, DateTimeKind.Utc).AddTicks(9791),
                            Text = "Another day, another post. #coding",
                            UserId = "user1"
                        });
                });

            modelBuilder.Entity("Cliq.Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "public");

                    b.HasData(
                        new
                        {
                            Id = "user1",
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "$2a$11$mYNNrhJ3UXAEq.GSiwQuKel1e8SvWWX8m97a0z9S3klPeQjBRB/mK",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = "user2",
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            Password = "$2a$11$wO5McvqbwyfAynTs028Akuyw8auYcZQOUdOncJIzD.d5psBRj6Hv2",
                            Username = "janesmith"
                        },
                        new
                        {
                            Id = "user3",
                            Email = "bob@example.com",
                            Name = "Bob Wilson",
                            Password = "$2a$11$zp99clQpriv/Qekw.HHGSudntEX4q05IkHEvFaYMIUmjrUyjd7/3K",
                            Username = "bobwilson"
                        });
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("text");

                    b.Property<string>("ViewersId")
                        .HasColumnType("text");

                    b.HasKey("PostId", "ViewersId");

                    b.HasIndex("ViewersId");

                    b.ToTable("PostUser", "public");

                    b.HasData(
                        new
                        {
                            PostId = "post1",
                            ViewersId = "user2"
                        },
                        new
                        {
                            PostId = "post1",
                            ViewersId = "user3"
                        },
                        new
                        {
                            PostId = "post2",
                            ViewersId = "user1"
                        },
                        new
                        {
                            PostId = "post2",
                            ViewersId = "user3"
                        });
                });

            modelBuilder.Entity("Cliq.Server.Models.Comment", b =>
                {
                    b.HasOne("Cliq.Server.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cliq.Server.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("ParentPostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cliq.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cliq.Server.Models.Post", b =>
                {
                    b.HasOne("Cliq.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.HasOne("Cliq.Server.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cliq.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ViewersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cliq.Server.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Cliq.Server.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
