// <auto-generated />
using System;
using Cliq.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cliq.Server.Migrations
{
    [DbContext(typeof(CliqDbContext))]
    partial class CliqDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cliq.Server.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "post1",
                            Date = new DateTime(2024, 11, 14, 5, 43, 59, 776, DateTimeKind.Utc).AddTicks(5481),
                            Text = "Hello world! This is my first post.",
                            UserId = "user1"
                        },
                        new
                        {
                            Id = "post2",
                            Date = new DateTime(2024, 11, 14, 17, 43, 59, 776, DateTimeKind.Utc).AddTicks(5510),
                            Text = "Excited to join this platform!",
                            UserId = "user2"
                        },
                        new
                        {
                            Id = "post3",
                            Date = new DateTime(2024, 11, 14, 23, 43, 59, 776, DateTimeKind.Utc).AddTicks(5513),
                            Text = "Another day, another post. #coding",
                            UserId = "user1"
                        });
                });

            modelBuilder.Entity("Cliq.Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "user1",
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "$2a$11$S.nyCZtkt89uQPm1.8t/hedPUrgh5GoQk3hsh3SMYikVg/DQKy79q",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = "user2",
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            Password = "$2a$11$VUB4LfbHhr/aQhUpxbDEXe1X7yb/qDs0CK8jRcTv6/j.8SS00mHha",
                            Username = "janesmith"
                        },
                        new
                        {
                            Id = "user3",
                            Email = "bob@example.com",
                            Name = "Bob Wilson",
                            Password = "$2a$11$BtLENedQGOkSALOZB4zMnObefixI/GmmrWWx6oLntoJdtIt/xNxr6",
                            Username = "bobwilson"
                        });
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.Property<string>("PostId")
                        .HasColumnType("text");

                    b.Property<string>("ViewersId")
                        .HasColumnType("text");

                    b.HasKey("PostId", "ViewersId");

                    b.HasIndex("ViewersId");

                    b.ToTable("PostUser");

                    b.HasData(
                        new
                        {
                            PostId = "post1",
                            ViewersId = "user2"
                        },
                        new
                        {
                            PostId = "post1",
                            ViewersId = "user3"
                        },
                        new
                        {
                            PostId = "post2",
                            ViewersId = "user1"
                        },
                        new
                        {
                            PostId = "post2",
                            ViewersId = "user3"
                        });
                });

            modelBuilder.Entity("Cliq.Server.Models.Post", b =>
                {
                    b.HasOne("Cliq.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.HasOne("Cliq.Server.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cliq.Server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ViewersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
