import React, { useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity,TextInput, StyleSheet, SafeAreaView } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

interface Comment {
  id: string;
  author: string;
  content: string;
  replies?: Comment[];
}

const dummyComments: Comment[] = [
  {
    id: '1',
    author: 'David',
    content: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat!',
    replies: [
      {
        id: '1-1',
        author: 'Emma',
        content: 'I agree!',
        replies: [
          {
            id: '1-1-1',
            author: 'Frank',
            content: 'Me too!',
          },
        ],
      },
      {
        id: '1-2',
        author: 'George',
        content: 'Interesting perspective.',
      },
    ],
  },
  {
    id: '2',
    author: 'Hannah',
    content: 'Thanks for sharing!',
    replies: [
      {
        id: '2-1',
        author: 'Ian',
        content: "You're welcome!",
      },
    ],
  },
];

const CommentTree: React.FC<{ comment: Comment; depth: number; onAddReply: (parentId: string, newReply: Comment) => void }> = ({ comment, depth, onAddReply }) => {
    const [collapsed, setCollapsed] = useState(false);
    const [replyText, setReplyText] = useState('');
    const [isReplying, setIsReplying] = useState(false);
  
    const handleReply = () => {
      if (replyText.trim()) {
        const newReply: Comment = {
          id: Date.now().toString(), // This should be generated by the backend in a real app
          author: 'Current User', // This should be the logged-in user's name
          content: replyText.trim(),
        };
        onAddReply(comment.id, newReply);
        setReplyText('');
        setIsReplying(false);
      }
    };
  
    return (
      <View style={[styles.commentContainer, { marginLeft: depth * 8 }]}>

        <View style={styles.commentContent}>
          <TouchableOpacity
            style={styles.collapseButton}
            onPress={() => setCollapsed(!collapsed)}
          >
            <View style={styles.verticalLine} />
          </TouchableOpacity>
          <View style={styles.commentBody}>
            <Text style={styles.commentAuthor}>{comment.author}</Text>
            {!collapsed && (
              <>
                <Text style={styles.commentText}>{comment.content}</Text>
                <View style={styles.actionButtons}>
                  <TouchableOpacity style={styles.actionButton}>
                    <Ionicons name="happy-outline" size={20} color="#1DA1F2" />
                    <Text style={styles.actionButtonText}>React</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.actionButton} onPress={() => setIsReplying(true)}>
                    <Ionicons name="chatbox-outline" size={20} color="#1DA1F2" />
                    <Text style={styles.actionButtonText}>Reply</Text>
                  </TouchableOpacity>
                </View>
                {isReplying && (
                  <View style={styles.replyContainer}>
                    <TextInput
                      style={styles.replyInput}
                      value={replyText}
                      onChangeText={setReplyText}
                      placeholder="Type your reply..."
                      multiline
                    />
                    <View style={styles.replyButtons}>
                      <TouchableOpacity style={styles.replyButton} onPress={() => setIsReplying(false)}>
                        <Text style={styles.replyButtonText}>Cancel</Text>
                      </TouchableOpacity>
                      <TouchableOpacity style={styles.replyButton} onPress={handleReply}>
                        <Text style={styles.replyButtonText}>Comment</Text>
                      </TouchableOpacity>
                    </View>
                  </View>
                )}
                {comment.replies &&
                  comment.replies.map((reply) => (
                    <CommentTree key={reply.id} comment={reply} depth={depth + 1} onAddReply={onAddReply} />
                  ))}
              </>
            )}
          </View>
        </View>
      </View>
    );
  };
  
  const CommentSection: React.FC<{ route: { params: { postId: string } } }> = ({ route }) => {
    const { postId } = route.params;
    const [comments, setComments] = useState(dummyComments);
  
    const addReply = (parentId: string, newReply: Comment) => {
      const updateReplies = (comments: Comment[]): Comment[] => {
        return comments.map(comment => {
          if (comment.id === parentId) {
            return {
              ...comment,
              replies: [...(comment.replies || []), newReply],
            };
          } else if (comment.replies) {
            return {
              ...comment,
              replies: updateReplies(comment.replies),
            };
          }
          return comment;
        });
      };
  
      setComments(updateReplies(comments));
    };
  
    return (
    <SafeAreaView style={styles.container}>
      <ScrollView style={styles.container}>
        {comments.map((comment) => (
          <CommentTree key={comment.id} comment={comment} depth={0} onAddReply={addReply} />
        ))}
      </ScrollView>
    </SafeAreaView>
    );
  };
  
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f0f2f5',
      padding: 16,
    },
    commentContainer: {
        marginTop: 8,
        marginBottom: 8,
      },
      commentContent: {
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: '#e1e4e8',
        borderRadius: 4,
        overflow: 'hidden',
      },
      collapseButton: {
        width: 24,
        backgroundColor: '#f6f8fa',
        alignItems: 'center',
      },
      verticalLine: {
        width: 2,
        backgroundColor: '#1DA1F2',
        flex: 1, // This will make the line fill the height of its container
      },
      commentBody: {
        flex: 1,
        padding: 8,
      },
    commentAuthor: {
      fontWeight: 'bold',
      marginBottom: 4,
    },
    commentText: {
      fontSize: 14,
      marginBottom: 8,
    },
    actionButtons: {
      flexDirection: 'row',
      marginTop: 8,
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 16,
    },
    actionButtonText: {
      marginLeft: 4,
      color: '#1DA1F2',
    },
    replyContainer: {
      marginTop: 8,
    },
    replyInput: {
      borderWidth: 1,
      borderColor: '#e1e4e8',
      borderRadius: 4,
      padding: 8,
      minHeight: 80,
    },
    replyButtons: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 8,
    },
    replyButton: {
      marginLeft: 8,
      padding: 8,
      backgroundColor: '#1DA1F2',
      borderRadius: 4,
    },
    replyButtonText: {
      color: 'white',
    },
  });
  
  export default CommentSection;