#!/usr/bin/env node
/**
 * Generates a dev-ip.generated.js file exporting a URL pointing to the local machine
 * Uses first non-internal IPv4 address on common private ranges.
 */
const os = require('os');
const fs = require('fs');
const path = require('path');

let PORT = process.env.DEV_API_PORT || '7188';
let PROTOCOL = process.env.DEV_API_PROTOCOL || 'https';

function pickIp() {
  const ifaces = os.networkInterfaces();
  const preferred = [];
  for (const name of Object.keys(ifaces)) {
    for (const iface of ifaces[name] || []) {
      if (iface.internal) continue;
      if (iface.family !== 'IPv4') continue;
      // Accept typical private ranges
      if (!/^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[0-1])\./.test(iface.address)) continue;
      preferred.push({ name, address: iface.address });
    }
  }
  // Prefer en0 / Wi-Fi typical names first
  preferred.sort((a,b) => {
    const score = (x) => (/en\d/.test(x.name) ? 0 : /wi-?fi/i.test(x.name) ? 1 : 5);
    return score(a) - score(b);
  });
  return preferred[0]?.address || null;
}

const ip = pickIp();
if (!ip) {
  console.warn('[gen-dev-ip] No LAN IPv4 found, keeping localhost.');
}

// If we have a LAN IP and user did not force HTTPS, default to HTTP port 5188 to avoid cert SAN issues
if (ip && ip !== 'localhost' && !process.env.DEV_FORCE_HTTPS && !process.env.DEV_API_PROTOCOL) {
  PROTOCOL = 'http';
  PORT = '5188';
}

const url = `${PROTOCOL}://${ip || 'localhost'}:${PORT}`;

const outPath = path.join(__dirname, '..', 'dev-ip.generated.js');
const content = `// AUTO-GENERATED by scripts/gen-dev-ip.js
// Set DEV_FORCE_HTTPS=1 to force https:// with port 7188 (self-signed cert must trust IP SAN!)
module.exports = { url: '${url}', ip: '${ip || ''}', port: '${PORT}', protocol: '${PROTOCOL}' };\n`;
fs.writeFileSync(outPath, content, 'utf8');
console.log(`[gen-dev-ip] Wrote ${outPath} with URL ${url}`);
